server:
  port: 8082
spring:
  application:
    name: boot-eureka-user
eureka:
  instance:
    prefer-ip-address: true     #优先ip调用
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/    #注册中心节点
