server:
  port: 8090
spring:
  application:
    name: boot-eureka-user
  zipkin:
    base-url: http://127.0.0.1:9411
    # 关闭服务发现，否则Spring Cloud会把zipkin的url当做服务名称
    discovery-client-enabled: false
    sender:
      type: web  # 设置使用http的方式传输数据
  sleuth:
    sampler:
      probability: 1  # 设置抽样采集率为100%，默认为0.1，即10%
eureka:
  instance:
    prefer-ip-address: true     #优先ip调用
  client:
    service-url:
#      defaultZone: http://127.0.0.1:8888/eureka/    #注册中心节点
      defaultZone: http://192.168.1.49:8888/eureka/,http://10.211.55.5:9999/eureka/    #注册中心节点
#修改Ribbon负载均衡算法
#boot-eureka-order:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#feign开启hystrix熔断器
feign:
  hystrix:
    enabled: true
