#高可用config服务
server:
  port: 12001
eureka:
  instance:
    prefer-ip-address: true     #优先ip调用
  client:
    service-url:
      defaultZone: http://192.168.1.49:8888/eureka/,http://10.211.55.5:9999/eureka/   #注册中心节点
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mrguanxs/config_repo.git    #配置文件仓库地址
