server:
  port: 9041
spring:
  application:
    name: zipkin-server
management:
  metrics:
    web:
      server:
        auto-time-requests: false
zipkin:
  collector:
    rabbitmq:
      addresses: 10.211.55.5:5672
      password: guest
      username: guest
      queue: zipkin
