server:
  port: 8080
#data source
spring:
# h2数据库，纯java编写的内存数据库，可做测试用,比较方便
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  h2: # 使用H2 控制台   访问页面http://localhost:8080/h2-console/，默认的数据库为jdbc:h2:mem:testdb
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  #加载hibernate自动更新数据库结构
#                validate               加载hibernate时，验证创建数据库表结构
#                create                  每次加载hibernate，重新创建数据库表结构，这就是导致数据库表数据丢失的原因。
#                create-drop        加载hibernate时创建，退出是删除表结构
  application:
    name: boot-ssh-provider   #配置服务名称
